version: '3'
services:
  # Frontend container
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules     
      - /usr/src/app/.next    
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Backend API container
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    env_file: 
      - .env
    # command: sh -c "node seedUser.js && node server.js"  # Runs seed first
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - app-network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    networks:
      - app-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3001:3000"  # Host 3001 → Grafana's default port 3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network
    restart: unless-stopped


volumes:
  mongo-data:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
