version: '3'
services:
  # Frontend container
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules     
      - /usr/src/app/.next    
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped

  # Backend API container
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    env_file: 
      - .env
    # command: sh -c "node seedUser.js && node server.js"  # Runs seed first
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - HUGGINGFACE_TOKEN=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
    restart: unless-stopped

  # MongoDB container Since we are using mongodb atlas
  # mongo:
  #   image: mongo:4.4
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: unless-stopped

# Define volumes for persistent data
volumes:
  mongo-data:
