name: Super-Linter and Functionality test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Everything and simple tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js (For ESLint to work)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
#Frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run Next.js ESLint
      working-directory: ./frontend
      run: npm run lint

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

#Backend
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test

    - name: Run GitHub Super-Linter
      uses: github/super-linter@v6
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_JAVASCRIPT_ES: true
